# Generated by Django 3.2 on 2021-05-03 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('minutes_to_prepare', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edition_date', models.DateTimeField(blank=True, null=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('picture', models.ImageField(default='default.jpg', upload_to='dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edition_date', models.DateTimeField(blank=True, null=True)),
                ('dishes', models.ManyToManyField(to='eMenu.Dish')),
            ],
        ),
    ]
