# Generated by Django 3.2 on 2021-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0002_rename_price_dish_price_in_dollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='dishes/default.jpg', upload_to='dishes'),
        ),
    ]
