# Generated by Django 3.2 on 2021-05-03 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eMenu', '0003_alter_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='edition_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
